import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="images/favicon.ico" />
        <title>Dawood Ahmad</title>
        <link rel="stylesheet" href="https://assets.snow562.com/css/shared.css" />
        <link rel="stylesheet" href="https://assets.snow562.com/css/navbar.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link crossOrigin="" rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&amp;display=swap" rel="stylesheet" />
      </head>
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
