import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <base href="https://assets.snow562.com/" />
        <link rel="icon" type="image/x-icon" href="images/favicon.ico" />
        <title>Dawood Ahmad</title>
        <link rel="stylesheet" href="css/shared.css" />
        <link rel="stylesheet" href="css/navbar.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link crossOrigin="" rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&amp;display=swap" rel="stylesheet" />
      </head>
      <body
        className={"antialiased"}
      >
        {children}
      </body>
    </html>
  );
}
